services:
  - type: web
    name: vyoma-backend
    runtime: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22.17.0
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
